CC=g++
OUTDIR=out

all: MakeThreeComponentVector MakeParticle

MakeThreeComponentVector:
	$(CC) -Wall -c ThreeComponentVector.cpp -o ThreeComponentVector.o

MakeParticle:
	$(CC) -Wall -c Particle.cpp -o Particle.o

